services:

  api:
    build:
      target: prod
    environment:
      PORT: "3001"
      NODE_ENV: production
      SEED_USERS_PATH: /data/users.json
    volumes: !override
      - api-db:/app/db
      - ./data:/data:ro
    
  client:
    build:
      target: prod
    environment:
      PORT: "3000"
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
    depends_on:
      - api
    volumes: !reset []
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 82:80
    depends_on:
      - api
      - client
    networks:
      - bankzero-network

volumes:
  api-db:
  api-node-modules:
  client-node-modules:

networks:
  bankzero-network:
  