services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      PORT: "3001"
      NODE_ENV: development
      SEED_USERS_PATH: /data/users.json
    volumes:
      - ./api:/app
      - api-node-modules:/app/node_modules
      - api-db:/app/db
      - ./data:/data:ro
    networks:
      - smartpump-network
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      PORT: "3000"
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
    depends_on:
      - api
    volumes:
      - ./client/app:/app/app
      - ./client/lib:/app/lib
      - ./client/public:/app/public
      - /app/node_modules
      - /app/.next
    networks:
      - smartpump-network
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 82:80
    depends_on:
      - api
      - client
    networks:
      - smartpump-network

volumes:
  api-db:
  api-node-modules:

networks:
  smartpump-network:
  