services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./api:/app
      - api-node-modules:/app/node_modules
    networks:
      - bankzero-network
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - bankzero-network
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 82:80
    depends_on:
      - api
      - client
    networks:
      - bankzero-network

volumes:
  api-node-modules:

networks:
  bankzero-network:
  